### ISSUE TITLE
 a single use case question

### ISSUE THREAD

**Issue by sancelot** [kmammou/v-hacd#128] opened 2022-10-03 09:12 UTC

**Comment by jankrassnigg** [comment] 2022-10-03 09:22
You edited your whole text away, I don't think that was intentional ?

Looking at the image, I don't think what you want is possible. However, I would add to the question that the slit in the table top (at the bottom of the image) is more concerning to me. I've seen similar artifacts in old VHACD but haven't checked yet whether the new version does the same. If this is done with the new version, is this a known artifact?

**Comment by jratcliff63367** [comment] 2022-10-03 14:30
I'm away from my computer right now. I will check on this later today or tomorrow and get back to you. Off the top of my head, it might be interesting to try disabling the shrinkwrap option and see if it is the culprit. Use -s false

Let me know if that is the cause.

**Comment by jratcliff63367** [comment] 2022-10-03 22:12
Woops, I was on my cell phone. I have access to my computer again now. Can you upload the file as a wavefront OBJ and I can take a look at it?

**Comment by jratcliff63367** [comment] 2022-10-07 16:14
Ok, fixed on 'master'. I changed the '-l' for logging to '-g' so there wouldn't be a name conflict.

**Closed by jratcliff63367** 2022-10-07 16:14 UTC
